### ISSUE TITLE
experimental-openを指定してもウィンドウが1つしか開かない

### ISSUE THREAD

**Issue by Negima1072** [akashic-games/akashic-cli#1201]
# 概要
```
akashic serve --target-service nicolive --experimental-open 4
```
のような形式でウィンドウ数を指定した場合、指定数のウィンドウが開かず１つのみが生成される。

# エラー
その際、生成されたウィンドウに以下のエラーが表示される。
```
TypeError: Cannot read properties of null (reading 'content')
    at ./src/client/operator/PlayOperator.ts.PlayOperator.calcWindowLayout (PlayOperator.ts:147:58)
    at PlayOperator.openNewClientInstance (PlayOperator.ts:66:45)
    at bootstrap.tsx:33:19
    at step (UserInformation.ts:16:3)
    at Object.next (UserInformation.ts:16:3)
    at fulfilled (UserInformation.ts:16:3)
    at invokeCallback (es6-promise.js:408:1)
    at publish (es6-promise.js:391:1)
    at MutationObserver.flush (es6-promise.js:128:1)
```
<img width="866" alt="スクリーンショット 2023-01-28 19 58 24" src="https://user-images.githubusercontent.com/67858442/215262945-4ada6d87-c6e8-4bb7-9eee-7a3410e0110a.png">

# 各種設定ファイル
### sandbox.config.js
```javascript
module.exports = {
  "warn": {
    "es6": false
  },
  "displayOptions": {
    "fitsToScreen": true
  },
  "windowSize": {
    "width": 540,
    "height": 300 
  }
};
```

# 環境
PC: MacBookPro(macOS Monterey 12.2.1)
Node: v18.13.0
npm: 9.4.0
```json
  "devDependencies": {
    "@akashic/akashic-engine": "^3.9.3",
    "@types/jest": "^29.0.0",
    "@types/node": "^18.7.16",
    "@typescript-eslint/eslint-plugin": "^5.36.2",
    "@typescript-eslint/parser": "^5.36.2",
    "eslint": "^8.23.0",
    "eslint-config-prettier": "8.5.0",
    "jest": "^29.0.2",
    "npm-run-all": "^4.1.5",
    "prettier": "2.7.1",
    "rimraf": "^3.0.2",
    "ts-jest": "^29.0.0",
    "typescript": "^4.8.3"
  },
  "dependencies": {
    "@akashic-extension/aimgui": "^1.0.2",
    "@akashic-extension/akashic-label": "^3.0.1"
  }
```

**Comment by xnv** [comment]
ありがとうございます。現象を確認しました。修正します。

**Comment by xnv** [comment]
最新の akashic-cli@2.16.11 で修正されましたのでご確認いただければと思います。

**Comment by Negima1072** [comment]
遅ればせながら確認いたしました。ありがとうございますm(_ _)m
